### ISSUE TITLE
Koodikatselmointi - palaute

### ISSUE THREAD

**Issue by shnigi** [sorja/twatter#1]
Katsoin projektia 25.9.2016 klo 14 - 15.

Hauskasti sattui melkein samanlainen ajatus projektille minkä itse keksin. Sivuston ulkoasu on vielä varmasti kesken, mutta muistuttaa kivasti 90 lukua! Huomaan kuitenkin yhtäläisyyksiä twitterin kanssa ja siitä vaikutteita varmaan on haettukin. 

Ensiksi silmään pisti repositorion outous. Oletko muistanut pushata kaiken repositorioon?  Repositorion rakenne on nimittäin vähän hassu. Tosin tämä on pieni harjoitustyö ja oletkin kasannut lähes kaiken koodin app.py tiedostoon. Sovelluksen kasvaessa olisi hyvä hajauttaa koodia tiedostoihin ja jaotella ne kansioihin. 

Static / css kansiossa sinulla on milligram kirjasto käytössä.  Tämä kannattaa jättää pois versionhallinnasta ja ladata projektikohtaisesti esimerkiksi bowerilla. Yleensäkään "vendor" koodia ei tule laittaa versionhallintaan.

Olet myös löytänyt kätevän templatelibraryn pythonin kanssa yhteensopivaksi. Myös tarvittavat muut kirjastot ladataan PIPillä, mikä helpottaa seuraavaa kehittäjää. Tästä plussaa.

app.py tiedostossa on kohta   SECRET_KEY = 'A0Zr98j/3yX R~XHH!jmN]LWX/,?RT' en ole varma mikä tämä tässä tapauksessa on, mutta koska tämä projekti on julkisena githubissa, salaisia avaimia ei sinne kannata puskea. 

Muutoin koodi on melko selkeää luettavaa, luokat ja routet ovat selkeästi nimetty. En keksi tästä juurikaan pahaa sanottavaa. Seuraavaan versioon olisikin mukava nähdä koodi pilkottuna omiin tiedostoihin ja jaoteltuina kansioittain. 

Hyvältä näyttää noin muuten.  Tämä onkin hyvä esimerkkiprojekti kuinka pienellä määrällä omaa koodia voi saada tietokantaa hyödyntävän sovelluksen pystyyn.

Kokeiltaessa sivua onnistuin rekisteröitymään, kirjautumaan ja lisäämään tekstiä. Kaikki näyttänee olevan kunnossa. Toki sivulla on paljon lorem ipsumia vielä täytteenä.

**Comment by sorja** [comment]
Hei,
kiitos kovasti palautteesta, oli joitain kohtia (esim secret_key) jotka olin tosiaan jättänyt kokonaan huomioimatta. Toit myös esille bower (joka on siis tuttu) ja olin hieman 50% / 50% jaksanko implementoida, mutta tutkin asiaa tarkemmin ja se on nyt sitten käytössä!

Kiitos paljon koodikatselmoinnistasi
